# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Yuxiao Li
repository: https://github.com/yetiiil/yetiiil.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: https://yetiiil.github.io # the base hostname & protocol for your site, e.g. http://example.com
google_scholar: https://scholar.google.com/citations?user=GjcJpncAAAAJ&hl=en&oi=ao
github: https://github.com/yetiiil
bluesky: https://bsky.app/profile/yuxiaoli.bsky.social
orcid: https://orcid.org/0009-0006-8181-0110
portrait: images/profile_picture.jpeg
description: "PhD student in Computer Science at Technical University of Munich. My research focuses on enhancing the reliability, robustness, and safety of AI models, with a particular interest in LLM robustness, factuality, and adversarial resilience. Currently, I am developing a lightweight language model designed to generate factually reliable text summaries, while also exploring methods to prevent LLMs from being manipulated into producing misleading or harmful content. My broader interests include evaluating and mitigating risks in AI systems and adversarial robustness to ensure safer and more trustworthy AI deployment."


# Build settings
# theme: minima
plugins:
  - jekyll-assets
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
